version: '3'

services:
  slave-1:
    image: jmeter
    volumes:
     - .:/mnt/jmeter
    command: -s -n -Jserver.rmi.localport=60000 -Jserver.rmi.ssl.keystore.file=/mnt/jmeter/rmi_keystore.jks 
  slave-2:
    image: jmeter
    volumes:
     - .:/mnt/jmeter
    command: -s -n -Jserver.rmi.localport=60000 -Jserver.rmi.ssl.keystore.file=/mnt/jmeter/rmi_keystore.jks 
  slave-3:
    image: jmeter
    volumes:
     - .:/mnt/jmeter
    command: -s -n -Jserver.rmi.localport=60000 -Jserver.rmi.ssl.keystore.file=/mnt/jmeter/rmi_keystore.jks 
